name := "duplication"
version := "0.1"
scalaVersion := "2.12.8"
libraryDependencies += "org.codefeedr" %% "codefeedr-core" %  "0.1.0"
libraryDependencies += "org.apache.flink" %% "flink-scala" % "1.7.0"
libraryDependencies += "org.apache.flink" %% "flink-streaming-scala" % "1.7.0"
libraryDependencies += "org.json4s" %% "json4s-native" % "3.6.5"
libraryDependencies += "org.json4s" %% "json4s-jackson" % "3.6.5"